### ISSUE TITLE
Error when specifying broadcast_port

### ISSUE THREAD

**Issue by alexdelprete** [gjr80/weewx-gw1000#27]
First of all, let me thank you for this driver, very well made and documented.

I installed it with default settings, but it didn't discover the GW1000 so it threw an error. In the settings I didn't find a way to specify the IP so I went to the wiki and found the options sections. So I specified some default settings in weewx.conf with comments, so if I need to change something I have what's needed in the config.

Since I wanted to understand why it didn't find the GW1000, I specified the broadcast_port option, but when I restarted weewx it threw the following error:

```
Mar 17 20:03:03 rpi4argon weewx-ecowitt[67057] INFO user.gw1000: driver version is 0.2.0
Mar 17 20:03:03 rpi4argon weewx-ecowitt[67057] INFO user.gw1000: GW1000 address is 10.1.10.118:45000
Mar 17 20:03:03 rpi4argon weewx-ecowitt[67057] INFO user.gw1000: poll interval is 60 seconds
Mar 17 20:03:03 rpi4argon weewx-ecowitt[67057] ERROR weewx.engine: Import of driver failed: %d format: a number is required, not str (<class 'TypeError'>)
Mar 17 20:03:03 rpi4argon weewx-ecowitt[67057] CRITICAL weewx.engine:     ****  Traceback (most recent call last):
Mar 17 20:03:03 rpi4argon weewx-ecowitt[67057] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/weewx/engine.py", line 119, in setupStation
Mar 17 20:03:03 rpi4argon weewx-ecowitt[67057] CRITICAL weewx.engine:     ****      self.console = loader_function(config_dict, self)
Mar 17 20:03:03 rpi4argon weewx-ecowitt[67057] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 1498, in loader
Mar 17 20:03:03 rpi4argon weewx-ecowitt[67057] CRITICAL weewx.engine:     ****      return Gw1000Driver(**config_dict[DRIVER_NAME])
Mar 17 20:03:03 rpi4argon weewx-ecowitt[67057] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 1860, in __init__
Mar 17 20:03:03 rpi4argon weewx-ecowitt[67057] CRITICAL weewx.engine:     ****      logdbg('broadcast address is %s:%d, socket timeout is %d seconds' % (self.broadcast_address,
Mar 17 20:03:03 rpi4argon weewx-ecowitt[67057] CRITICAL weewx.engine:     ****  TypeError: %d format: a number is required, not str
Mar 17 20:03:03 rpi4argon weewx-ecowitt[67057] CRITICAL __main__: Unable to load driver: %d format: a number is required, not str
Mar 17 20:03:03 rpi4argon weewx-ecowitt[67057] CRITICAL __main__:     ****  Waiting 60 seconds then retrying...
```

This is the config of the driver:

```
# Options for 'GW1000': https://github.com/gjr80/weewx-gw1000/wiki/Available-Config-Options
[GW1000]

# The driver to use:
driver = user.gw1000

# If ip_address is not specified the GW1000 driver will attempt to locate GW1000 on the LAN and use the first GW1000 found
ip_address = 10.1.10.118

# Port number used when communicating with the the GW1000. Optional, number. Default is 45000
port = 45000

# Interval in seconds used to poll the GW1000 for data. Optional, number. Default is 60
poll_interval = 60

# The IP address to be used when sending a UDP broadcast to identify GW1000 devices on the network. Optional, string. Default is 255.255.255.255
broadcast_address = 255.255.255.255  

# The port number to be used when sending a UDP broadcast to identify GW1000 devices on the network. Optional, number. Default is 46000
#broadcast_port = 46000
```

Thanks for any advice.

**Comment by gjr80** [comment]
This issue has been fixed under issue #28. I will release an updated driver version that includes the fix in coming days. In the meantime if you want to install the updated driver there are instructions in my post at issue #28.
