### ISSUE TITLE
weeconfig not found

### ISSUE THREAD

**Issue by iverjohnson** [gjr80/weewx-gw1000#66]
When running the --test-device, I get this error:
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/etc/weewx/bin/user/gw1000.py", line 344, in <module>
    import weecfg
ModuleNotFoundError: No module named 'weecfg'

This is on the Weewx 5.0

**Comment by iverjohnson** [comment]
This was a permissions and db issue.  Disregard, all working now!
