### ISSUE TITLE
Python package "six" required

### ISSUE THREAD

**Issue by tobytes** [gjr80/weewx-gw1000#78]
Operation system: Ubuntu 24.04
Python version: 3.12.3
Weewx version: 5.1.0-4 installed via apt package

I tried to install the extension as described in the installation instruction on a fresh weewx installation. 
`weectl extension install https://github.com/gjr80/weewx-gw1000/releases/latest/download/gw1000.zip`

**Current behavior:**
I got the following error:

```
Using configuration file /etc/weewx/weewx.conf
Install extension 'https://github.com/gjr80/weewx-gw1000/releases/latest/download/gw1000.zip' (y/n)? y
Extracting from zip archive /tmp/tmp300bu736
Traceback (most recent call last):
  File "/usr/share/weewx/weecfg/__init__.py", line 715, in get_extension_installer
    __import__('install')
  File "/tmp/tmp85zgwas9/gw1000/install.py", line 59, in <module>
ModuleNotFoundError: No module named 'six'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/weewx/weectl.py", line 75, in <module>
    main()
  File "/usr/share/weewx/weectl.py", line 67, in main
    namespace.func(namespace)
  File "/usr/share/weewx/weectllib/__init__.py", line 90, in dispatch
    namespace.action_func(config_dict, namespace)
  File "/usr/share/weewx/weectllib/extension_cmd.py", line 116, in install_extension
    ext.install_extension(namespace.source, no_confirm=namespace.yes)
  File "/usr/share/weewx/weecfg/extension.py", line 130, in install_extension
    extension_name = self._install_from_file(test_fd.name, filetype)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/extension.py", line 170, in _install_from_file
    extension_name = self.install_from_dir(extension_dir)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/extension.py", line 181, in install_from_dir
    installer_path, installer = weecfg.get_extension_installer(extension_dir)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/weewx/weecfg/__init__.py", line 717, in get_extension_installer
    raise ExtensionError("Cannot find 'install' module in %s" % extension_installer_dir)
weecfg.ExtensionError: Cannot find 'install' module in /tmp/tmp85zgwas9/gw1000/
```

**Expected behavior:**
It seems the library "[six](https://pypi.org/project/six/)" is a requirement to install the extension.
It would be helpful to have this mentioned in the installation instruction.

**Solution:**
Install library six:
e.g. `apt install python3-six`

Thank you for the hard work!

**Comment by gjr80** [comment]
Thank you. Whilst I would have preferred to have the installer gracefully fail if `six` was not found that is not possible with the current WeeWX extension installer machinery. Instead we will rely on a rather messy installation and additional install instructions.
